# Generated by Django 5.2.15 on 2026-06-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exposuremedia",
            name="content_warning",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="주의 문구"
            ),
        ),
        migrations.AddField(
            model_name="exposuremedia",
            name="media_url",
            field=models.URLField(
                blank=True, default="", max_length=1000, verbose_name="미디어 URL"
            ),
        ),
        migrations.AlterField(
            model_name="exposuremedia",
            name="asset_ref",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="에셋 참조"
            ),
        ),
    ]
