# Generated by Django 5.2.16 on 2026-07-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_exposuremedia_content_warning_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeCompass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "life_goal",
                    models.TextField(
                        blank=True, default="", verbose_name="의미 있는 삶의 목표"
                    ),
                ),
                (
                    "study_domain",
                    models.TextField(
                        blank=True, default="", verbose_name="1만 시간 학습 영역"
                    ),
                ),
                (
                    "goal_1y",
                    models.TextField(blank=True, default="", verbose_name="1년 목표"),
                ),
                (
                    "goal_5y",
                    models.TextField(blank=True, default="", verbose_name="5년 목표"),
                ),
                (
                    "goal_10y",
                    models.TextField(blank=True, default="", verbose_name="10년 목표"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
            options={
                "verbose_name": "삶의 나침반",
                "verbose_name_plural": "삶의 나침반",
            },
        ),
    ]
