# Generated by Django 5.2.16 on 2026-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lifecompass"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateCheckin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arousal",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "무기력/멍함"),
                            (2, "가라앉음/무료함"),
                            (3, "안정(창 안)"),
                            (4, "긴장/들뜸"),
                            (5, "과각성/충동"),
                        ],
                        verbose_name="각성도(1~5)",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="몸 부위"
                    ),
                ),
                (
                    "sensation",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="감각"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="신호의 이유/맥락",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="상태 이동 행동",
                    ),
                ),
                (
                    "arousal_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "무기력/멍함"),
                            (2, "가라앉음/무료함"),
                            (3, "안정(창 안)"),
                            (4, "긴장/들뜸"),
                            (5, "과각성/충동"),
                        ],
                        null=True,
                        verbose_name="행동 후 각성도",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
            options={
                "verbose_name": "상태 체크인",
                "verbose_name_plural": "상태 체크인",
                "ordering": ["-created_at"],
            },
        ),
    ]
