# Generated by Django 5.2.16 on 2026-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_statecheckin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopingAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True, verbose_name="행동"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="분류")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("up", "끌어올리기(무기력→활력)"),
                            ("down", "가라앉히기(과각성→안정)"),
                            ("ground", "중심잡기(창 안 안정)"),
                        ],
                        max_length=10,
                        verbose_name="방향",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="효과/경험"
                    ),
                ),
                (
                    "effort",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="실행 난이도(1~3)"
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(default=False, verbose_name="사용자 추가"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "대처 행동",
                "verbose_name_plural": "대처 행동",
                "ordering": ["category", "id"],
            },
        ),
    ]
