# Generated by Django 5.2.16 on 2026-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_copingaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningConcept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="식별키"),
                ),
                (
                    "group_no",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="그룹 번호"
                    ),
                ),
                (
                    "group_title",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="그룹명"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="개념명")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="영문명"
                    ),
                ),
                (
                    "originator",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="제안 학자"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="요약"),
                ),
                (
                    "connection",
                    models.TextField(
                        blank=True, default="", verbose_name="내 회복과의 연결"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="내 메모"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "학습 개념",
                "verbose_name_plural": "학습 개념",
                "ordering": ["group_no", "id"],
            },
        ),
    ]
