# Generated by Django 5.2.16 on 2026-07-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_learningconcept"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningconcept",
            name="detail",
            field=models.TextField(blank=True, default="", verbose_name="자세히(해설)"),
        ),
    ]
